### ISSUE TITLE
Typo: Missing slash in closing tag

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html-ruby#2]
Slash of closing tag of ruby element in some examples is missing.

EXAMPLE5
`<ruby><rb>京<rb>都<rb>市<rt>きょう<rt>と<rt>し`**`<ruby>`**
`<ruby><rb>京<rb>都<rb>市<rp>（<rt>きょう<rt>と<rt>し<rp>）`**`<ruby>`**

EXAMPLE8
`<ruby><rb>京<rb>都<rb>市<rt>きょう<rt>と<rt>し`**`<ruby>`**

**Comment by frivoal** [comment]
Nice catch, thank you!
Fixed in https://github.com/w3c/html-ruby/commit/bb461dfcefb5e287f993062fbac327231dc67f42
